@Back_HostAddress = http://localhost:5001

GET {{Back_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Back_HostAddress}}/pizza/
Accept: application/json

###
GET {{Back_HostAddress}}/pizza/2
Accept: application/json

###
POST {{Back_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false,
    "Sabor": "Maracuya",
    "Extra": false
}

###
PUT {{Back_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false,
    "Sabor": "Maracuya",
    "Extra": true
}

###
DELETE {{Back_HostAddress}}/pizza/3

###